# Each of these represents a single R Shiny application and
# acts as a convenience for getting a development version of
# the apps running quickly.

version: "3.7"
services:
  dashboard:
    build:
      context: ./packages/dashboard
    ports:
      - 3000:3838

  hello-world:
    build:
      context: ./packages/hello-world
    ports:
      - 3001:3838
    volumes:
      - ./packages/hello-world:/srv/shiny-server
