name: Terraform Validation

on:
  push:
    paths:
      - infrastructure/**/*

defaults:
  run:
    working-directory: infrastructure

jobs:
  validate:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    strategy:
      max-parallel: 5
      matrix:
        path:
          - environments
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0
          terraform_wrapper: false

      - name: Validate
        run: |
          cd ${{ matrix.path }}
          terraform init -backend=false
          terraform validate
